{{ config(materialized="table") }}

SELECT
    GEOLOCATION_ZIP_CODE_PREFIX,
    GEOLOCATION_LAT,
    GEOLOCATION_LNG,
    UPPER(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY,
    UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE
from {{ source("ecommerce_raw", "geolocation") }}
WHERE GEOLOCATION_ZIP_CODE_PREFIX IS NOT NULL