{{config(materialized='table')}}

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    AVG(DATE_DIFF(CAST(ORDER_APPROVED_AT  AS DATETIME), CAST(ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS approval_days,
    AVG(DATE_DIFF(CAST(ORDER_DELIVERED_CARRIER_DATE AS DATETIME), CAST(ORDER_APPROVED_AT AS DATETIME), DAY)) AS shipping_days,
    AVG(DATE_DIFF(CAST(ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME), CAST(ORDER_DELIVERED_CARRIER_DATE AS DATETIME), DAY)) AS delivery_days,
    AVG(DATE_DIFF(CAST(ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME), CAST(ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS av_real_time,
    AVG(DATE_DIFF(CAST(ORDER_ESTIMATED_DELIVERY_DATE AS DATETIME), CAST(ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS estimated_time
FROM {{ref('orders')}}
WHERE ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY 1, 2, 3