{{config(materialized='table')}}

SELECT
    c.CUSTOMER_ID AS CUSTOMER_ID,
    c.CUSTOMER_UNIQUE_ID AS CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_ZIP_CODE_PREFIX AS ZIP_CODE_PREFIX,
    c.CUSTOMER_CITY AS CITY,
    c.CUSTOMER_STATE AS STATE,
    g.GEOLOCATION_LAT AS LAT,
    g.GEOLOCATION_LNG AS LNG,
    ROW_NUMBER() OVER (PARTITION BY g.GEOLOCATION_ZIP_CODE_PREFIX ORDER BY C.CUSTOMER_ID) AS  value_count
FROM {{ref('customers')}} AS c
 LEFT JOIN {{ref('geolocation')}} AS g
 ON c.CUSTOMER_ZIP_CODE_PREFIX = g.GEOLOCATION_ZIP_CODE_PREFIX
WHERE CUSTOMER_ID IS NOT NULL