{{config(materialized='table')}}

WITH esto AS (
SELECT
    o.ORDER_ID AS ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_STATUS AS ORDER_STATUS,
    oi.ORDER_ITEM_ID,
    o.ORDER_PURCHASE_TIMESTAMP,
    p.PRODUCT_ID,
    SUM(oi.PRICE) AS sales,
    AVG(DATE_DIFF(CAST(o.ORDER_APPROVED_AT  AS DATETIME), CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS approval_days,
    AVG(DATE_DIFF(CAST(o.ORDER_DELIVERED_CARRIER_DATE AS DATETIME), CAST(o.ORDER_APPROVED_AT AS DATETIME), DAY)) AS shipping_days,
    AVG(DATE_DIFF(CAST(o.ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME), CAST(o.ORDER_DELIVERED_CARRIER_DATE AS DATETIME), DAY)) AS delivery_days,
    AVG(DATE_DIFF(CAST(o.ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME), CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS av_real_time,
    AVG(DATE_DIFF(CAST(o.ORDER_ESTIMATED_DELIVERY_DATE AS DATETIME), CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATETIME), DAY)) AS estimated_time,
FROM {{ref('orders')}} AS o
    LEFT JOIN {{ref('order_items')}} AS oi
    ON o.ORDER_ID = oi.ORDER_ID
    LEFT JOIN {{ref('products')}} AS p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY 1, 2, 3, 4, 5, 6
)
SELECT
    ORDER_STATUS,
    COUNT(ORDER_ID)
FROM esto
GROUP BY 1